
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        check-latest: true

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install protoc-gen-go and grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v $(go list ./... | grep -v /integration)
